services:
  BD:
    image: mysql:8.0
    container_name: Base_de_datos
    environment:
      MYSQL_ROOT_PASSWORD: 1l0h
      MYSQL_DATABASE: MiBD
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1l0h
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

